### ISSUE TITLE
UnsupportedOperationException: This isn't a hierarchical URI.

### ISSUE THREAD

**Issue by eileenfan** [tobykurien/GoogleApps#35]
//package name: com.tobykurien.google_news
//version: 1.17
//target sdk version: android-18
 java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
 	at android.net.Uri.getQueryParameter(Uri.java:1663)
 	at com.tobykurien.google_news.webviewclient.WebClient.getLoadUri(WebClient.java:92)
 	at com.tobykurien.google_news.webviewclient.WebClient.shouldOverrideUrlLoading(WebClient.java:50)
 	at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:261)
 	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:363)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by protectivedad** [comment]
I'm having the same problem. When I run the package on Android 4.0.3 and I go to the news screen after loading the app crashes. Is there any resolution except for don't use the news?

**Comment by protectivedad** [comment]
Changing the user agent changes what google sends and stops the crashing.

But with a Tablet or Phone user agent the images are stretched vertically and cut in half. The text displays across boundaries in portrait and in landscape mode there is a large unused space on the left.
