### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by eileenfan** [tobykurien/GoogleApps#37]
//package name: com.tobykurien.google_news
//version: 1.14
//target sdk version: android-18
 java.lang.NullPointerException
 	at com.tobykurien.google_news.GoogleNewsActivity$2.onLongClick(GoogleNewsActivity.java:133)
 	at android.view.View.performLongClick(View.java:4276)
 	at android.webkit.WebView.access$601(WebView.java:239)
 	at android.webkit.WebView$PrivateAccess.super_performLongClick(WebView.java:1775)
 	at android.webkit.WebViewClassic.performLongClick(WebViewClassic.java:4455)
 	at android.webkit.WebView.performLongClick(WebView.java:2105)
 	at android.webkit.WebViewClassic$PrivateHandler.handleMessage(WebViewClassic.java:7402)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by tobykurien** [comment]
Is it possible to include some additional information about what you were doing to cause the error? What device are you testing on?
